# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
accumpaste <- function(x, sid) {
    .Call('_shiny_alluvial_accumpaste', PACKAGE = 'shiny.alluvial', x, sid)
}

rcpp_hello_world <- function() {
    .Call('_shiny_alluvial_rcpp_hello_world', PACKAGE = 'shiny.alluvial')
}

